services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
      
  evaluation-service:
    build: ./evaluation-service
    container_name: evaluation-worker
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - code-temp-volume:/usr/src/app/temp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./evaluation-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    restart: unless-stopped
  ai-service:
    build: ./ai-service
    container_name: ai-service
    ports:
      - "5002:5002"
    env_file:
      - ./ai-service/.env
    depends_on:
      - evaluation-service
    restart: unless-stopped
volumes:
  rabbitmq-data:
  code-temp-volume: