services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped
      
  evaluation-service:
    build: ./evaluation-service
    container_name: evaluation-worker
    ports:
      - "5001:5001"
    volumes:
      # We create a shared volume for temporary code files.
      - code-temp-volume:/usr/src/app/temp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./evaluation-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_URI=amqp://rabbitmq
      - RESULT_EXCHANGE=results_exchange
    restart: unless-stopped
      
volumes:
  rabbitmq-data:
  code-temp-volume: